version: "3"
services:
    backend:
        build: .
        env_file: .env
        container_name: telegpt-server
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app