version: "3"
services:
    backend:
        env_file: .env
        container_name: telegpt-server
        build:
            context: ./
            dockerfile: Dockerfile-server
        image: telegpt/telegpt-server
        ports:
            - "5000:5000"
        volumes:
            - ./:/usr/src/app