FROM node:18

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

COPY package*.json ./
RUN npm run build

# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source

COPY . .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "npm", "run", "start" ]